x-app-secrets: &app-secrets
  - database_password
  - lti_private_key
  - canvas_api_client_secret
  - session_secret
  - state_encryption_key
  - oauth_token_encryption_keyring
  - seb_quit_password

services:
  postgres:
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_PASSWORD_FILE: /run/secrets/database_password
    secrets:
      - database_password

  migrate:
    environment: &secret-file-environment
      DATABASE_PASSWORD:
      DATABASE_PASSWORD_FILE: /run/secrets/database_password
      LTI_PRIVATE_KEY:
      LTI_PRIVATE_KEY_FILE: /run/secrets/lti_private_key
      CANVAS_API_CLIENT_SECRET:
      CANVAS_API_CLIENT_SECRET_FILE: /run/secrets/canvas_api_client_secret
      SESSION_SECRET:
      SESSION_SECRET_FILE: /run/secrets/session_secret
      STATE_ENCRYPTION_KEY:
      STATE_ENCRYPTION_KEY_FILE: /run/secrets/state_encryption_key
      OAUTH_TOKEN_ENCRYPTION_KEYRING:
      OAUTH_TOKEN_ENCRYPTION_KEYRING_FILE: /run/secrets/oauth_token_encryption_keyring
      SEB_QUIT_PASSWORD:
      SEB_QUIT_PASSWORD_FILE: /run/secrets/seb_quit_password
    secrets: *app-secrets

  app:
    environment: *secret-file-environment
    secrets: *app-secrets

  cleanup:
    environment: *secret-file-environment
    secrets: *app-secrets

  encrypt-oauth-tokens:
    environment: *secret-file-environment
    secrets: *app-secrets

secrets:
  database_password:
    file: ${SECRETS_DIRECTORY:-./secrets}/database_password
  lti_private_key:
    file: ${SECRETS_DIRECTORY:-./secrets}/lti_private_key
  canvas_api_client_secret:
    file: ${SECRETS_DIRECTORY:-./secrets}/canvas_api_client_secret
  session_secret:
    file: ${SECRETS_DIRECTORY:-./secrets}/session_secret
  state_encryption_key:
    file: ${SECRETS_DIRECTORY:-./secrets}/state_encryption_key
  oauth_token_encryption_keyring:
    file: ${SECRETS_DIRECTORY:-./secrets}/oauth_token_encryption_keyring
  seb_quit_password:
    file: ${SECRETS_DIRECTORY:-./secrets}/seb_quit_password
