package org.kentdenver.sebcanvas.model;

import com.google.cloud.firestore.annotation.DocumentId;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents Safe Exam Browser settings for a Canvas quiz.
 * This class has been migrated from JPA to Firestore.
 *
 * In the Firestore data model:
 * - Each document represents settings for one quiz
 * - The document ID is generated by Firestore (UUID)
 * - The quizId field provides the link to the associated quiz
 */
@Data
@NoArgsConstructor
public class QuizSebSetting {
    /**
     * Unique identifier for this setting document.
     * This is a Firestore generated ID, not the quiz ID.
     */
    @DocumentId
    private String id;

    /**
     * The ID of the quiz this setting applies to.
     * This field is indexed in Firestore for efficient lookups.
     */
    private String quizId;

    /**
     * Whether SEB is required for this quiz.
     * If true, students must use Safe Exam Browser to access the quiz.
     */
    private boolean sebRequired;

    /**
     * The Browser Exam Key for SEB validation.
     * This is used to verify that students are using the correct SEB configuration.
     */
    private String browserExamKey;

    /**
     * The Config Key for additional SEB validation.
     * This provides a second layer of validation if configured.
     */
    private String configKey;

    /**
     * Reference to a stored SEB config file if using a custom configuration.
     * In Firestore, this could be a reference to a file in Cloud Storage.
     */
    private String sebConfigFileId;
}