#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

usage() {
  cat >&2 <<EOF
usage: $0 [CLOUDRUN_ENV_FILE] [OUTPUT_FILE]

Renders the small Canvas Theme Desktop JavaScript loader required for protected
Classic Quiz and New Quiz routes. Run after prepare.sh, then upload the output
file to the active Canvas account or sub-account theme.
EOF
}

if [[ $# -gt 2 ]]; then
  usage
  exit 64
fi

script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$script_directory/cloud-run-config.sh" ]]; then
  # Release bundle layout.
  # shellcheck disable=SC1091
  source "$script_directory/cloud-run-config.sh"
else
  # Source repository layout.
  # shellcheck disable=SC1091
  source "$script_directory/../deploy/cloud-run-config.sh"
fi

cloudrun_load_environment "${1:-cloudrun.env}"
cloudrun_validate_base
cloudrun_require_commands jq

tool_url="$TOOL_URL"
if [[ -f "$BOOTSTRAP_DIRECTORY/tool_url" && ! -L "$BOOTSTRAP_DIRECTORY/tool_url" ]]; then
  tool_url="$(<"$BOOTSTRAP_DIRECTORY/tool_url")"
fi
cloudrun_validate_url TOOL_URL "$tool_url"
detector_url_json="$(jq -Rn --arg value "${tool_url%/}/js/canvas-seb-detector.js" '$value')"

output_file="${2:-$STATE_DIRECTORY/canvas-theme-loader.js}"
output_directory="$(dirname "$output_file")"
mkdir -p "$output_directory"
[[ -d "$output_directory" && ! -L "$output_directory" ]] ||
  cloudrun_die "Canvas theme output directory must be a regular directory: $output_directory"
[[ ! -e "$output_file" || ! -L "$output_file" ]] ||
  cloudrun_die "refusing to replace Canvas theme loader symlink: $output_file"
temporary_file="$(mktemp "${output_file}.tmp.XXXXXX")"

cat >"$temporary_file" <<EOF
// Generated by Safe Online Exam. Upload this as the active Canvas Theme
// Desktop JavaScript for the account or sub-account that owns protected exams.
(function () {
  "use strict";

  const detectorUrl = $detector_url_json;
  const assessmentPath = /^\\/courses\\/\\d+\\/(?:quizzes\\/\\d+\\/take|assignments\\/\\d+)(?:\\/|$)/;
  const newQuizAuthoringPath = /^\\/courses\\/\\d+\\/assignments\\/\\d+\\/(?:build|settings|moderate|reports|exports)(?:\\/|$)/;

  if (!assessmentPath.test(window.location.pathname) || newQuizAuthoringPath.test(window.location.pathname)) {
    return;
  }
  if (document.querySelector('script[data-canvas-seb-detector="true"]')) {
    return;
  }

  const script = document.createElement("script");
  script.src = detectorUrl;
  script.async = true;
  script.dataset.canvasSebDetector = "true";
  document.head.appendChild(script);
})();
EOF
chmod 600 "$temporary_file"
mv "$temporary_file" "$output_file"

cat <<EOF
Generated Canvas Theme Desktop JavaScript:
  $output_file

Upload this exact file to the active Canvas account/sub-account theme before
testing a protected assessment. Then reload Canvas and confirm it requests:
  ${tool_url%/}/js/canvas-seb-detector.js
EOF
